name: demo_botnet_hybrid
channels:
  - defaults
dependencies:
  - python=3.7.6
  - cryptography=2.8
  - black=19.10b0
  - flake8=3.7.9
  - pip=20.0.2
  - pip:
    - pyinstaller==3.6
    - pysocks==1.7.1
    - cmd2==1.0.1